#!/bin/bash
# Script to manage frpc


CONFIG_PATH="/opt/homebrew/etc/frp/frpc.ini"
LOG_PATH="/opt/homebrew/var/log/frpc.log"
FRPC_PID_FILE="/opt/homebrew/var/run/frpc.pid"

start_frpc() {
  if [ -f "$FRPC_PID_FILE" ] && kill -0 $(cat "$FRPC_PID_FILE"); then
    echo "frpc is already running."
  else
    echo "Starting frpc..."
    nohup frpc -c "$CONFIG_PATH" > "$LOG_PATH" 2>&1 &
    echo $! > "$FRPC_PID_FILE"
    echo "frpc started. Logs are being recorded in $LOG_PATH"
  fi
}

stop_frpc() {
  if [ -f "$FRPC_PID_FILE" ] && kill -0 $(cat "$FRPC_PID_FILE"); then
    echo "Stopping frpc..."
    kill $(cat "$FRPC_PID_FILE") && rm -f "$FRPC_PID_FILE"
    echo "frpc stopped."
  else
    echo "frpc is not running."
  fi
}

status_frpc() {
  if [ -f "$FRPC_PID_FILE" ] && kill -0 $(cat "$FRPC_PID_FILE"); then
    echo "frpc is running."
  else
    echo "frpc is not running."
  fi
}

log_frpc() {
  if [ -f "$LOG_PATH" ]; then
    tail -f "$LOG_PATH"
  else
    echo "Log file $LOG_PATH does not exist."
  fi
}

show_help() {
  echo "Usage: $0 {start|stop|status|log|-h}"
  echo "  start  - Start frpc"
  echo "  stop   - Stop frpc"
  echo "  status - Show frpc status"
  echo "  log    - Show frpc log"
  echo "  -h     - Display this help message"
}

case "$1" in
  start)
    start_frpc
    ;;
  stop)
    stop_frpc
    ;;
  status)
    status_frpc
    ;;
  log)
    log_frpc
    ;;
  -h|--help)
    show_help
    ;;
  *)
    echo "Invalid option. Use -h to see the help message."
    exit 1
esac

